version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    # Look for a `package.json` and `package-lock.json` in the root
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Automatically add these labels to PRs
    labels:
      - "dependencies"
      - "security"
    # Auto-assign PRs (optional)
    # assignees:
    #   - "smmariquit"
